-- Step 22: Derived Insights table for synthesis agent output
--
-- Stores insights generated by the synthesis loop (Phase 3 from Architecture v2).
-- The synthesis agent runs weekly, analyzes accumulated data, and writes
-- patterns, correlations, predictions, and recommendations here.
-- These insights surface in ask_brain queries and entity dossiers.

CREATE TABLE IF NOT EXISTS brain.derived_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_type TEXT NOT NULL,              -- pattern, correlation, prediction, recommendation
  description TEXT NOT NULL,               -- natural language insight
  evidence JSONB NOT NULL,                 -- entity_ids, activity_ids, data points
  confidence FLOAT DEFAULT 0.5,
  scope JSONB,                             -- which entity types/categories this applies to
  entity_ids UUID[],                       -- entities this insight references
  taxonomy_categories TEXT[],              -- acumen categories this insight relates to
  status TEXT DEFAULT 'active',            -- active, superseded, expired, rejected
  expires_at TIMESTAMPTZ,
  review_needed BOOLEAN DEFAULT false,     -- flag for CEO review
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by TEXT DEFAULT 'synthesis_agent'
);

CREATE INDEX IF NOT EXISTS idx_derived_insights_status
  ON brain.derived_insights(status);

CREATE INDEX IF NOT EXISTS idx_derived_insights_type
  ON brain.derived_insights(insight_type);

CREATE INDEX IF NOT EXISTS idx_derived_insights_created
  ON brain.derived_insights(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_derived_insights_categories
  ON brain.derived_insights USING GIN(taxonomy_categories);

CREATE INDEX IF NOT EXISTS idx_derived_insights_entity_ids
  ON brain.derived_insights USING GIN(entity_ids);

NOTIFY pgrst, 'reload schema';
